import type { Metadata } from "next";
import { Montserrat_Alternates} from "next/font/google"; //importing the Montserrat_Alternates font from google fonts one I will use througout my website
import "./globals.css";
import Navbar from "./(components)/Navbar"; //importing our navbar component to call it here in our layout.tsx since these are the things that get rendered persistently accross all routes that are childre of it
import Header from "./(components)/Header"; //importing our header component so it can be displayed on our fixed layout
import KevinCard from "./(components)/KevinCard";

const montserratAlternates = Montserrat_Alternates({ //this function is provided by nextJS, we pass it the subsets, weights, and styles that I specify and returns a object with the font information. className that will apply font and styles as well as variable to use in my styles
  subsets: ["latin"], //specifying character subset
  variable: "--font-montserrat-alternates", //creates css variable for the font
  weight: "400", //specifies weight of font reg is 400 and bold is 700
});

export const metadata: Metadata = {
  title: "Kevin's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className = {montserratAlternates.variable}>
      <body className= "bg-figmaGray"> 
        <Navbar/>
        <KevinCard/>
        {children}
      </body>
    </html>
  );

  // line 26 -> Added the montserratAlternates.variable to the html tag to apply the font to the entire website
  // line 27 -> Made background color the custom figmaGray I added to my tailwind.css file. Making it persistent across all routes
}
